CREATE TABLE [dbo].[Booking] (
    [numBookingID]        INT             IDENTITY (1, 1) NOT NULL,
    [varBookingNo]        VARCHAR (50)    NULL,
    [numCustomerID]       INT             NULL,
    [dtDeliveryDate]      DATETIME        NULL,
    [varFromAddress]      VARCHAR (100)   NULL,
    [varToAddress]        VARCHAR (100)   NULL,
    [numDistance]         DECIMAL (18, 2) NULL,
    [numGoodsTypeID]      INT             NULL,
    [numWeight]           DECIMAL (18, 2) NULL,
    [numPrice]            DECIMAL (18, 2) NULL,
    [bitIsApproved]       BIT             NULL,
    [numDriverID]         INT             NULL,
    [dtApprovedDateTime]  DATETIME        NULL,
    [bitIsStarted]        BIT             NULL,
    [dtStartedDateTime]   DATETIME        NULL,
    [bitIsCompleted]      BIT             NULL,
    [dtCompletedDateTime] DATETIME        NULL,
    [bitActive]           BIT             NULL,
    [dtCreatedDate]       DATETIME        NULL,
    [numCreatedID]        INT             NULL,
    [dtEditedDate]        DATETIME        NULL,
    [numEditedID]         INT             NULL,
    [dtDeletedDate]       DATETIME        NULL,
    [numDeletedID]        INT             NULL,
    CONSTRAINT [PK_Booking] PRIMARY KEY CLUSTERED ([numBookingID] ASC),
    CONSTRAINT [FK_Booking_Customer] FOREIGN KEY ([numCustomerID]) REFERENCES [dbo].[Customer] ([numCustomerID]),
    CONSTRAINT [FK_Booking_Driver] FOREIGN KEY ([numDriverID]) REFERENCES [dbo].[Driver] ([numDriverID]),
    CONSTRAINT [FK_Booking_GoodsType] FOREIGN KEY ([numGoodsTypeID]) REFERENCES [dbo].[GoodsType] ([numGoodsTypeID])
);

